# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
  MACOSX_DEPLOYMENT_TARGET: '10.6'
  OPENSSL_VERSION: '1.0.2q'
  OPENSSL_ROOT_DIR: $(Agent.TempDirectory)/openssl
  PythonVersion27: '2.7.14'
  PythonVersion34: '3.4.4'
  PythonVersion35: '3.5.4'
  PythonVersion36: '3.6.4'
  PythonVersion37: '3.7.0'
  PythonVersionPre: '3.8.0a1'

jobs:
- job: 'MacOS_OpenSSL'
  condition: false
  displayName: 'MacOS Shared OpenSSL'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: sudo xcode-select --switch /Applications/Xcode_9.4.1.app
    displayName: 'Select Xcode 9.4.1'
  - script: source ./build_openssl_osx.sh
    displayName: 'Build OpenSSL'
    env:
      DEST: $(Agent.TempDirectory)
      LDFLAGS: -mmacosx-version-min=$(MACOSX_DEPLOYMENT_TARGET)
      CFLAGS: -mmacosx-version-min=$(MACOSX_DEPLOYMENT_TARGET)
  - task: PublishPipelineArtifact@0
    displayName: 'Publish OpenSSL artifact'
    inputs:
      artifactName: openssl.macos.$(OPENSSL_VERSION)
      targetPath: $(OPENSSL_ROOT_DIR)
- job: 'MacOS'
  condition: false
  dependsOn: 'MacOS_OpenSSL'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python 2.7:
        PythonVersion: '$(PythonVersion27)'
        PythonBin: 'python2'
      Python 3.4:
        PythonVersion: '$(PythonVersion34)'
        PythonBin: 'python3'
      Python 3.5:
        PythonVersion: '$(PythonVersion35)'
        PythonBin: 'python3'
      Python 3.6:
        PythonVersion: '$(PythonVersion36)'
        PythonBin: 'python3'
      Python 3.7:
        PythonVersion: '$(PythonVersion37)'
        PythonBin: 'python3'
  steps:
  - script: sudo xcode-select --switch /Applications/Xcode_9.4.1.app
    displayName: 'Select Xcode 9.4.1'
  - script: source ./install_python_osx.sh
    displayName: 'Install Official Python'
  - script: curl https://bootstrap.pypa.io/get-pip.py | /usr/local/bin/$(PythonBin) && /usr/local/bin/$(PythonBin) -m pip install -r dev_requirements.txt
    displayName: 'Install dependencies'
  - task: DownloadPipelineArtifact@0
    displayName: 'Download OpenSSL artifact'
    inputs:
      artifactName: openssl.macos.$(OPENSSL_VERSION)
      targetPath: $(OPENSSL_ROOT_DIR)
  - script: /usr/local/bin/$(PythonBin) setup.py bdist_wheel
    displayName: 'Build uAMQP Wheel'
    env:
      CMAKE_OSX_DEPLOYMENT_TARGET: $(MACOSX_DEPLOYMENT_TARGET)
      CMAKE_OSX_ARCHITECTURES: 'i386;x86_64'
      UAMQP_USE_OPENSSL: 'True'
      UAMQP_REBUILD_PYX: 'True'
      OPENSSL_INCLUDE_DIR: $(OPENSSL_ROOT_DIR)/include
      LDFLAGS: -mmacosx-version-min=$(MACOSX_DEPLOYMENT_TARGET) -L$(OPENSSL_ROOT_DIR)/lib
      CFLAGS: -mmacosx-version-min=$(MACOSX_DEPLOYMENT_TARGET) -I$(OPENSSL_ROOT_DIR)/include
  - script: ls ./dist
    displayName: 'Check output'
  - task: PublishPipelineArtifact@0
    displayName: 'Publish wheel artifact'
    inputs:
      artifactName: wheel.macos.$(PythonVersion)
      targetPath: 'dist'
- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      x64 - Python 2.7:
        PythonVersion: '$(PythonVersion27)'
        PythonArchitecture: 'x64'
      x64 - Python 3.4:
        PythonVersion: '$(PythonVersion34)'
        PythonArchitecture: 'x64'
      x64 - Python 3.5:
        PythonVersion: '$(PythonVersion35)'
        PythonArchitecture: 'x64'
      x64 - Python 3.6:
        PythonVersion: '$(PythonVersion36)'
        PythonArchitecture: 'x64'
      x64 - Python 3.7:
        PythonVersion: '$(PythonVersion37)'
        PythonArchitecture: 'x64'
      x64 - Python Prerelease:
        PythonVersion: '$(PythonVersionPre)'
        PythonArchitecture: 'x64'
      x86 - Python 2.7:
        PythonVersion: '$(PythonVersion27)'
        PythonArchitecture: 'x86'
      x86 - Python 3.4:
        PythonVersion: '$(PythonVersion34)'
        PythonArchitecture: 'x86'
      x86 - Python 3.5:
        PythonVersion: '$(PythonVersion35)'
        PythonArchitecture: 'x86'
      x86 - Python 3.6:
        PythonVersion: '$(PythonVersion36)'
        PythonArchitecture: 'x86'
      x86 - Python 3.7:
        PythonVersion: '$(PythonVersion37)'
        PythonArchitecture: 'x86'
      x86 - Python Prerelease:
        PythonVersion: '$(PythonVersionPre)'
        PythonArchitecture: 'x86'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(PythonVersion)'
      architecture: '$(PythonArchitecture)'
    displayName: 'Use Python Version'
    condition: ne(variables['PythonVersion'], variables['PythonVersionPre'])
  - powershell: |
      choco install python3 --pre --$(PythonArchitecture) --yes --no-progress --params "/InstallDir:C:\PythonPre"
      Write-Host "##vso[task.prependpath]C:\PythonPre\Scripts"
      Write-Host "##vso[task.prependpath]C:\PythonPre"
    displayName: 'Install Python Version'
    condition: eq(variables['PythonVersion'], variables['PythonVersionPre'])
  - powershell: |
     Invoke-WebRequest -UseBasicParsing -Uri https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi -OutFile VCForPython27.msi
     Start-Process -Wait -NoNewWindow msiexec.exe -ArgumentList "/i VCForPython27.msi /quiet /qn /norestart /log VCForPython27.log ALLUSERS=1"
     Get-Content VCForPython27.log
    displayName: 'Install Microsoft Visual C++ Compiler for Python 2.7'
    condition: eq(variables['PythonVersion'], variables['PythonVersion27'])
  - powershell: |
     python --version
     Invoke-WebRequest -UseBasicParsing -Uri https://bootstrap.pypa.io/get-pip.py | Select-Object -ExpandProperty Content | python
     python -m pip install -r dev_requirements.txt
    displayName: 'Install dependencies'
  - script: python setup.py bdist_wheel
    displayName: 'Build uAMQP Wheel'
    env:
      UAMQP_REBUILD_PYX: 'True'
    condition: ne(variables['PythonVersion'], variables['PythonVersion34'])
  - script: dir dist
    displayName: 'Check output'
    condition: ne(variables['PythonVersion'], variables['PythonVersion34'])
  - task: PublishPipelineArtifact@0
    displayName: 'Publish wheel artifact'
    inputs:
      artifactName: wheel.win.$(PythonArchitecture).$(PythonVersion)
      targetPath: 'dist'
    condition: ne(variables['PythonVersion'], variables['PythonVersion34'])
- job: 'Linux'
  condition: false
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python 2.7:
        PythonVersion: '$(PythonVersion27)'
      Python 3.4:
        PythonVersion: '$(PythonVersion34)'
      Python 3.5:
        PythonVersion: '$(PythonVersion35)'
      Python 3.6:
        PythonVersion: '$(PythonVersion36)'
      Python 3.7:
        PythonVersion: '$(PythonVersion37)'
      Python Prerelease:
        PythonVersion: '$(PythonVersionPre)'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(PythonVersion)'
    displayName: 'Use Python Version'
    condition: ne(variables['PythonVersion'], variables['PythonVersionPre'])
  - script: |
     export DEBIAN_FRONTEND=noninteractive
     sudo add-apt-repository -y ppa:deadsnakes/ppa
     sudo apt-get update
     sudo apt-get -q -y install python3.8 python3.8-distutils python3.8-venv python3.8-dev
     sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1
    displayName: 'Install Python Version'
    condition: eq(variables['PythonVersion'], variables['PythonVersionPre'])
  - script: python --version && curl -sS https://bootstrap.pypa.io/get-pip.py | python && python -m pip install -r dev_requirements.txt
    displayName: 'Install dependencies'
  - script: python setup.py bdist_wheel
    displayName: 'Build uAMQP Wheel'
    env:
      UAMQP_REBUILD_PYX: 'True'
  - script: ls ./dist
    displayName: 'Check output'
  - task: PublishPipelineArtifact@0
    displayName: 'Publish wheel artifact'
    inputs:
      artifactName: wheel.manylinux.$(PythonVersion)
      targetPath: 'dist'
- job: 'LinuxTest'
  condition: false
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python 2.7:
        PythonVersion: '$(PythonVersion27)'
      Python 3.4:
        PythonVersion: '$(PythonVersion34)'
      Python 3.5:
        PythonVersion: '$(PythonVersion35)'
      Python 3.6:
        PythonVersion: '$(PythonVersion36)'
      Python 3.7:
        PythonVersion: '$(PythonVersion37)'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(PythonVersion)'
  - script: curl https://bootstrap.pypa.io/get-pip.py | python && python -m pip install -r dev_requirements.txt
    displayName: 'Install dependencies'
  - script: pytest tests --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'Run Tests'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Linux - Python $(PythonVersion)'
    condition: succeededOrFailed()