parameters:
  ArtifactList: []

steps:
  - ${{ each artifact in parameters.ArtifactList }}:
    - download: current
      displayName: "Download ${{ artifact }}"
      artifact: ${{ artifact }}
      timeoutInMinutes: 5