trigger: none
pr: none

variables:
  OpenSSLVersion: '1.0.2t'

jobs:
  - job: 'OpenSSL'

    pool:
      vmImage: 'macOS-10.15'

    strategy:
      matrix:
        MacOS 10.6:
          MacOSXDeploymentTarget: '10.6'
        MacOS 10.9:
          MacOSXDeploymentTarget: '10.9'

    steps:
      - script: sudo xcode-select --switch /Applications/Xcode_9.4.1.app
        displayName: 'Select Xcode 9.4.1'

      - script: sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
        displayName: 'Install MacOS headers'

      - script: source ./build_openssl_osx.sh
        displayName: 'Build OpenSSL'
        env:
          CFLAGS: -mmacosx-version-min=$(MacOSXDeploymentTarget)
          DEST: $(Build.ArtifactStagingDirectory)
          LDFLAGS: -mmacosx-version-min=$(MacOSXDeploymentTarget)
          MACOSX_DEPLOYMENT_TARGET: $(MacOSXDeploymentTarget)
          OPENSSL_VERSION: $(OpenSSLVersion)

      - task: PublishPipelineArtifact@0
        displayName: 'Publish OpenSSL artifact'
        inputs:
          artifactName: openssl-macosx$(MacOSXDeploymentTarget)
          targetPath: $(Build.ArtifactStagingDirectory)/openssl
