parameters:
  versionSpec: '3.x'
  architecture: 'x64'

steps:
  # use
  - task: UsePythonVersion@0
    displayName: "Use Python $(PythonVersion)"
    inputs:
      versionSpec: ${{ parameters.versionSpec }}
      architecture: ${{ parameters.architecture }}
